name: Deploy Staging

on:
  push:
    branches: [ "staging" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy Staging
      uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.MY_RENDER_SERVICE_ID_STAGING }}
        api_key: ${{ secrets.MY_RENDER_API_KEY }}
        wait_deploy: true